// Copies a rendered journey into the site: WebP slides under public/slides/<id>/ and the
// captions under lib/journeys/, plus a registry the SlideJourney component reads.
//
//   node export-site.mjs journeys/index.json
import { execFileSync } from 'node:child_process';
import fs from 'node:fs';
import path from 'node:path';
import { fileURLToPath } from 'node:url';

const HERE = path.dirname(fileURLToPath(import.meta.url));
const SITE = process.env.SITE || path.resolve(HERE, '..', 'site');

const journeyFile = path.resolve(process.argv[2]);
const journey = JSON.parse(fs.readFileSync(journeyFile, 'utf8'));
const name = path.basename(journeyFile, '.json');
// A section's own page ('/ladder', '/memory') is that section's index journey.
const segs = journey.page.replace(/^\//, '').split('/');
const id = segs.length === 1 ? `${segs[0]}/index` : segs.join('/');

// cwebp where it exists; otherwise Pillow, which encodes WebP on any machine with Python.
function toWebp(png, out) {
  try {
    execFileSync('cwebp', ['-quiet', '-q', '88', png, '-o', out]);
  } catch {
    execFileSync('python3', ['-c', 'import sys; from PIL import Image; Image.open(sys.argv[1]).save(sys.argv[2], "WEBP", quality=88, method=6)', png, out]);
  }
}
const plain = (s) => String(s || '').replace(/\*/g, '');

const outDir = path.join(SITE, 'public', 'slides', id);
fs.mkdirSync(outDir, { recursive: true });

const slides = journey.slides.map((s) => {
  const png = path.join(HERE, 'frames', name, 'site', `${s.id}.png`);
  toWebp(png, path.join(outDir, `${s.id}.webp`));
  return { id: s.id, src: `/slides/${id}/${s.id}.webp`, title: plain(s.title), caption: s.caption };
});

// Remove images of slides this journey no longer has, one named file at a time.
const keep = new Set(journey.slides.map((s) => `${s.id}.webp`));
for (const file of fs.readdirSync(outDir)) {
  if (file.endsWith('.webp') && !keep.has(file)) fs.unlinkSync(path.join(outDir, file));
}

const libDir = path.join(SITE, 'lib', 'journeys');
fs.mkdirSync(libDir, { recursive: true });
fs.writeFileSync(
  path.join(libDir, `${id.replace(/\//g, '-')}.json`),
  `${JSON.stringify({ id, title: journey.chapter, slides }, null, 2)}\n`,
);

const files = fs.readdirSync(libDir).filter((f) => f.endsWith('.json')).sort();
const registry = [
  '// Generated by the slide export. One entry per page journey, keyed by its id.',
  ...files.map((f, i) => `import j${i} from './${f}';`),
  '',
  `export const JOURNEYS = Object.fromEntries([${files.map((_, i) => `j${i}`).join(', ')}].map((j) => [j.id, j]));`,
  '',
];
fs.writeFileSync(path.join(libDir, 'index.ts'), registry.join('\n'));

console.log(`${id}: ${slides.length} slides exported`);
