// Generated by the slide export. One entry per page journey, keyed by its id.
import j0 from './ladder-adapters-and-fine-tuning.json';
import j1 from './ladder-context.json';
import j2 from './ladder-continued-pretraining.json';
import j3 from './ladder-custom-pretraining.json';
import j4 from './ladder-distillation.json';
import j5 from './ladder-index.json';
import j6 from './ladder-instructions.json';
import j7 from './ladder-reinforcement-fine-tuning.json';
import j8 from './ladder-tools-and-the-loop.json';
import j9 from './memory-index.json';
import j10 from './memory-long-context-is-not-memory.json';
import j11 from './memory-six-architectures.json';
import j12 from './memory-the-ten-million-token-question.json';
import j13 from './memory-what-the-benchmarks-measure.json';
import j14 from './memory-what-we-have-measured.json';

export const JOURNEYS = Object.fromEntries([j0, j1, j2, j3, j4, j5, j6, j7, j8, j9, j10, j11, j12, j13, j14].map((j) => [j.id, j]));
