// Generated by the slide export. One entry per page journey, keyed by its id.
import j0 from './memory-index.json';
import j1 from './memory-long-context-is-not-memory.json';
import j2 from './memory-six-architectures.json';
import j3 from './memory-the-ten-million-token-question.json';
import j4 from './memory-what-the-benchmarks-measure.json';
import j5 from './memory-what-we-have-measured.json';

export const JOURNEYS = Object.fromEntries([j0, j1, j2, j3, j4, j5].map((j) => [j.id, j]));
