/**
 * The single-picture target-state wall chart.
 *
 * Deliberately not a manifest figure: it is one large authored SVG generated by
 * scripts/build-wall-chart.mjs, shown in a pan container because it is wider
 * than any content column and is meant to be zoomed, printed, and taken away.
 */
import { wallChartAsOf } from '@/lib/shared';

export interface WallChartProps {
  src?: string;
  title?: string;
  caption?: string;
}

export function WallChart({
  src = '/diagrams/target-state.svg',
  title = 'The agentic enterprise, on one page',
  caption = 'Fourteen layers with their control point, key mechanisms, and the products that serve them, grouped into the seven planes. The ten cross-cutting concerns run as columns across every layer, marked where each layer owns or enforces them, with their own product categories below. The four deterministic zones sit underneath as boundaries no model decision crosses. Products are named for orientation as of ' +
    wallChartAsOf +
    ': representative, not exhaustive, and not endorsements.',
}: WallChartProps) {
  return (
    <figure className="not-prose my-8 w-full max-w-none rounded-2xl border bg-fd-background p-4 shadow-sm sm:p-6 xl:-mx-12 xl:w-[calc(100%+6rem)] print:break-inside-avoid print:shadow-none">
      <header className="mb-4 flex flex-col gap-3 sm:flex-row sm:items-start sm:justify-between">
        <div className="max-w-3xl">
          <p className="m-0 text-[0.6875rem] font-semibold uppercase tracking-[0.14em] text-fd-muted-foreground">
            Reference diagram
          </p>
          <h2 className="mb-0 mt-1 text-lg font-semibold tracking-tight sm:text-xl">{title}</h2>
        </div>
        <div className="flex shrink-0 flex-wrap gap-2 print:hidden">
          <a
            href={src}
            target="_blank"
            rel="noreferrer"
            className="rounded-lg border px-3 py-1.5 text-xs font-medium hover:bg-fd-accent"
          >
            Open full size
          </a>
          <a href={src} download className="rounded-lg border px-3 py-1.5 text-xs font-medium hover:bg-fd-accent">
            Download SVG
          </a>
        </div>
      </header>

      <a
        href={src}
        target="_blank"
        rel="noreferrer"
        className="block overflow-hidden rounded-lg border bg-white focus-visible:outline-none focus-visible:ring-2 focus-visible:ring-fd-ring"
        aria-label={`${title}. Opens the full-size diagram in a new tab.`}
      >
        {/* eslint-disable-next-line @next/next/no-img-element */}
        <img src={src} alt={title} className="block h-auto w-full" />
      </a>

      <figcaption className="mt-4 text-sm leading-6 text-fd-muted-foreground">
        {caption} <span className="print:hidden">Click the diagram to open it full size.</span>
      </figcaption>
    </figure>
  );
}
